### ISSUE TITLE
[Bug]: decompiler fails to unpack generator

### ISSUE THREAD

**Issue by tombousso** [thuml/depyf#23]
### Your current environment

latest depyf

### 🐛 Describe the bug

Decompiler fails to create the correct code for unpacking generators. This resulted in a crash when trying to use `depyf.prepare_debug` on a model.

To reproduce:
```
def f():
    a, b = (None for _ in (1, 2))
    print('hi')

f()

import depyf
src = depyf.decompile(f)
print(src)

ctx = {}
exec(compile(src, 'noname', 'exec'), ctx)
ctx['f']()
```
Output:
```
hi
def f():
    """original function name <genexpr> is illegal, use a temp name."""
    
    
    def __temp_1(comp_arg_0):
        for __temp_2 in comp_arg_0:
            _ = __temp_2
            yield None
            continue
        return None
    
    
    __temp_3 = __temp_1(iter((1, 2)))
    a = __temp_3[0]
    b = __temp_3[1]
    print('hi')
    return None

Traceback (most recent call last):
  File "/.../test.py", line 13, in <module>
    ctx['f']()
  File "noname", line 14, in f
TypeError: 'generator' object is not subscriptable
```
Issue is that
```
    a = __temp_3[0]
    b = __temp_3[1]
```
is not allowed because generators cannot be indexed.

**Comment by youkaichao** [comment]
@tombousso thanks for the interest! https://github.com/thuml/depyf/pull/25 should fix it. Can you try it?

which model are you trying to compile? normally `torch.compile` should inline the generator expression, that's why I didn't hit this error before. I added the support anyway. It should work now.

**Comment by tombousso** [comment]
Yes it works, thanks for the quick fix @youkaichao!

I'm testing compilation on a variant of llama model using NVIDIA transformer engine. (Still have issue #24 when trying to use `depyf.prepare_debug`).
